language: php

sudo: false

dist: trusty

php:
  - 5.6
    env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'
  - 7.0
    env: 'COMPOSER_FLAGS="--prefer-source"'
  - 7.1
    env: 'COMPOSER_FLAGS="--prefer-source"'

global:
  - REPORT_EXIT_STATUS=1

before_script:
  - composer self-update
  - composer install ${COMPOSER_FLAGS} --no-interaction --dev

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/coveralls -v --exclude-no-stmt

matrix:
  fast_finish: true
